### ISSUE TITLE
test for Nil and throw exception with better error message

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/rebuilder#39]
# Problem

Rollbar is reporting rebuilder failures like this:

> `[rebuilder] production - New Error: NoMethodError: undefined method`>' for nil:NilClass https://rollbar.com/everypolitician/rebuilder/items/532/`

(...which leads to https://github.com/everypolitician/rebuilder/blob/edc0a614852a1f9992a89d96d7d2d00810d6ab0d/app.rb#L54 )

Much too indirect and cryptic.
# Proposed Solution

Rebuilder code tests for the not-infrequent `Nil` problem and throws a more helpful diagnostic/error message? 

I know _I_ don't know, but a rebuilder engineer might know what the underlying failure is, and reword the diagnostic accordingly.
# Acceptance Criteria

More helpful error message appears in the EveryPolitician #rollbar Slack channel when this happens.

**Comment by chrismytton** [comment]
The error is coming from [this line of code in ruby-git](https://github.com/schacon/ruby-git/blob/v1.3.0/lib/git/lib.rb#L936).

When I briefly looked into this before there was no _obvious_ pattern to which rebuilds would fail with this error, so I think it's either a transient git error, or it's a bug with ruby-git. The only other reference I could find to this error is https://github.com/schacon/ruby-git/issues/138, which was a transient error. I guess because of the sheer quantity of rebuilds we're doing we could be hitting this occasional bug fairly regularly. The [code that is supposed to set the `exitstatus` variable in ruby-git is using threads](https://github.com/schacon/ruby-git/blob/v1.3.0/lib/git/lib.rb#L924-L928), so I suspect there's some non-threadsafe things going on.

More generally perhaps this is the impetus we need to look into a more "modern" (read: complicated) ruby library such as [rugged](https://github.com/libgit2/rugged). Though that comes with its own problems as you have to use a custom Heroku buildpack to even install libgit2, and [creating a commit](https://github.com/libgit2/rugged#writing-to-a-repository) becomes non-trivial with that 😞

**Comment by chrismytton** [comment]
For now I've muted that error on Rollbar so they don't come into Slack.

**Comment by tmtmtmtm** [comment]
At what level of transience is the issue? i.e. can we catch and retry in these cases?

**Comment by chrismytton** [comment]
As of #70 we're no longer using `with_git_repo` or `ruby-git`. so we should no longer see issues of this variety. Any errors with the _build_ will now happen in the shell script, which we are capturing the full output of for inclusion in Rollbar errors.
